Select chain
diekuche/gutenberg pull request #105
Opened 2023-02-27 14:36 UTC by Xyzjesus

## Задача по верстке: прикладывайте скриншот результата верстки, рядом скриншот макета, что бы я мог сравнить.
![D5D34070-944B-45D6-820C-E7B4C26AF497](https://user-images.githubusercontent.com/62913761/221591294-4c62c722-1df7-4458-8c20-f73b509e2f24.jpeg)

## Задача по логике: краткое описание того, что было сделано, если что-то сложное то можно приложить видео
![F915F093-0A1D-4935-805D-116DEC4AF0F7](https://user-images.githubusercontent.com/62913761/221592024-0b6dcbc1-695b-47d9-9cf8-38e275c64847.jpeg)

# Ссылка на issue:

![AE1F86B4-75A3-42B7-BDC5-40FF3447A844](https://user-images.githubusercontent.com/62913761/221592187-a9886e3a-d936-4b5f-810e-c94382973022.jpeg)
haven't implemented icons for tokens yet

2023-03-02 10:12 UTC, Xyzjesus commented
![Screenshot 2023-03-02 at 14 11 50](https://user-images.githubusercontent.com/62913761/222398817-3ef5edff-1b66-47c4-b761-fd89f9fa5640.png)
![Screenshot 2023-03-02 at 14 12 10](https://user-images.githubusercontent.com/62913761/222398902-d7844a03-3933-4044-9780-83828516be65.png)

2023-03-13 07:52 UTC, Spaider15 requested changes

2023-03-13 07:52 UTC, Spaider15 commented on package.json
> +    "@types/lodash": "^4.14.191",
а зачем нам типы для лодаша? у нас ведь нет его

2023-03-13 07:52 UTC, Spaider15 commented on src/components/Swap/Swap.tsx
> +import Ps from "../Tokens/PS/Ps";
Все эти токены по сути являются копипастой стилей, сделай один компонент который принимает весь динамический текст и иконку, и переиспользуй его

2023-03-13 07:52 UTC, Spaider15 commented on src/components/Wallet/Wallet.tsx
> +    fetchAddress();
initKeplr асинхронная функция, но здесь ты не дожидаешься ее ответа, иниализация может быть еще не закончена, а ты уже адрес просишь

2023-03-13 18:11 UTC, Spaider15 approved these changes

2023-03-13 18:11 UTC, merged