issue125-1
diekuche/gutenberg pull request #127
Opened 2023-04-05 11:16 UTC by scsi9

## Задача по верстке: прикладывайте скриншот результата верстки, рядом скриншот макета, что бы я мог сравнить.

## Задача по логике: краткое описание того, что было сделано, если что-то сложное то можно приложить видео

# Ссылка на issue
layout - 
![image](https://user-images.githubusercontent.com/17857895/230064794-8ec65cd0-1a0f-41a0-b4f8-705d999be90b.png)
figma - 
![image](https://user-images.githubusercontent.com/17857895/230064893-905190be-96e9-4781-9b38-f5e325ff9520.png)
first parts

2023-04-05 11:40 UTC, Spaider15 requested changes

2023-04-05 11:40 UTC, Spaider15 commented on src/components/Pools/Pools.module.css
> +.ar {
назови все классы в этом файле нормально, без сокращений, и используй camelCase
проверь весь файл!

2023-04-05 11:40 UTC, Spaider15 commented on src/components/Pools/Pools.module.css
> +  display: flex;
у кнопки бордер другой в дизайне

2023-04-06 08:42 UTC, scsi9 commented
layout - 
![image](https://user-images.githubusercontent.com/17857895/230323516-94a1a5ab-4da7-420b-bb1e-56b39e67008e.png)
fix - class name
add component My investment

2023-04-07 11:21 UTC, scsi9 commented
layout  - 
![image](https://user-images.githubusercontent.com/17857895/230600597-4594f162-0cb4-426d-8c03-315e98170b25.png)

2023-04-07 12:12 UTC, CyberBirdie commented
1. My investment и all pools — болд 700. 

2. all pools — цвет как у My investment #E2FB5F. Сейчас тут стоит какой-то другой желтый. 

3. Добавить бордер rgba(115, 237, 201, 0.2)
<img width="491" alt="Screenshot 2023-04-07 at 19 59 27" src="https://user-images.githubusercontent.com/112537530/230605197-31afd52e-f61e-4539-bb54-7514500eefba.png">

4. Padding: 10px, 28px, 16px, 28px
<img width="256" alt="Screenshot 2023-04-07 at 20 02 10" src="https://user-images.githubusercontent.com/112537530/230605477-b652976f-3e54-4604-8ced-02dfddee6cd0.png">

5. background: rgba(124, 196, 219, 0.05);
border: 1px solid rgba(115, 237, 201, 0.2);
backdrop-filter: blur(10px);
border-radius: 16px;
<img width="665" alt="Screenshot 2023-04-07 at 20 03 23" src="https://user-images.githubusercontent.com/112537530/230605705-92294572-92a0-48e1-ab47-b929a24a0fe2.png">

6. background: rgba(21, 34, 38, 0.15);
border: 1px solid rgba(115, 237, 201, 0.2);
backdrop-filter: blur(10px);
border-radius: 10px;
<img width="505" alt="Screenshot 2023-04-07 at 20 04 27" src="https://user-images.githubusercontent.com/112537530/230605824-e7598c06-957a-4b42-bcee-450a2f1a45a0.png">

7. Списки отбиваются линиями border: 1px solid rgba(115, 237, 201, 0.05);
+ сделать падинг слева и справа одинаковый 40px
Total liquidity подвинуть правее, чуть-чуть поближе к Volume
<img width="601" alt="Screenshot 2023-04-07 at 20 05 32" src="https://user-images.githubusercontent.com/112537530/230606020-16ed8273-492f-40ec-87ea-77ce6eb28462.png">

8. Ховер 
background: rgba(67, 151, 178, 0.05);
<img width="706" alt="Screenshot 2023-04-07 at 20 07 16" src="https://user-images.githubusercontent.com/112537530/230606158-a4365124-89cc-4104-ae00-1b96b3b08bcb.png">

9. Стрелочку по центру и все эти плашки сделать одной высоты
<img width="626" alt="Screenshot 2023-04-07 at 20 11 04" src="https://user-images.githubusercontent.com/112537530/230606662-e9fc2c22-cf67-4744-957a-d8c39f71af55.png">

2023-04-11 08:35 UTC, Spaider15 approved these changes

2023-04-11 08:35 UTC, Spaider15 commented on src/components/Pools/MyPools/MyPools.index.module.css
> +td {
Этот стиль применится на все td на всем проекте, или сделай его вложенным под класс или назови его как нибудь

2023-04-11 08:36 UTC, merged