add input component
diekuche/gutenberg pull request #13
Opened 2022-09-09 07:32 UTC by Xyzjesus

## Задача по верстке: прикладывайте скриншот результата верстки, рядом скриншот макета, что бы я мог сравнить.
![image](https://user-images.githubusercontent.com/62913761/189295879-c811c8c2-4745-48a4-bde0-4b7d03e2a148.png)
![image](https://user-images.githubusercontent.com/62913761/189295976-12411736-9ddd-41c2-aaaa-8ece6c68a75c.png)

## Задача по логике: краткое описание того, что было сделано, если что-то сложное то можно приложить видео
создал инпут, вложив его в лейбл +враппер. инпут не встает в 100% label -- пришлось выравнивать вручную (96%)

# Ссылка на issue:
https://github.com/diekuche/gutenberg/issues/3#issue-1365679426

2022-09-09 07:33 UTC, Xyzjesus commented
заметил, что текст placeholder отличается, сейчас поправлю

2022-09-09 07:37 UTC, Xyzjesus commented
поправил цвет placeholder'а
![image](https://user-images.githubusercontent.com/62913761/189297335-a27a4dfc-1e78-4e99-aedf-67aef33767e3.png)

2022-09-09 11:43 UTC, Spaider15 requested changes

2022-09-09 11:43 UTC, Spaider15 commented on src/components/Input/Input.tsx
> +class Input extends React.Component {
Давай использовать функциональные компоненты вместо классовых, классы уже устарели

2022-09-09 11:43 UTC, Spaider15 commented on src/components/Input/Input.tsx
> +        <div className={styles.wrapper}>
Я думаю здесь нам враппер не нужен, создай компонент главной страницы, и добавь туда хедер и инпут
сверстай там флексами плиз, убери position: 'absolute'

2022-09-09 11:43 UTC, Spaider15 commented on src/components/Input/Input.tsx
> +                <h2>Token's Name:</h2>
Не уверен что h2 хорошая идея использовать для лейбла инпута, замени на просто div

2022-09-09 11:43 UTC, Spaider15 commented on src/components/Input/Input.tsx
> +                You can specify any name you like. But it is better to come up with something original
Оберни этот текст в тег плиз

2022-09-09 11:43 UTC, Spaider15 commented on src/components/Input/Input.tsx
> +                <input className={styles.input} type='text' placeholder='Jhon’s USD Obligation'/>
placeholder, label, type, value и остальные пропсы должны приходить через пропсы, на главной где его переиспользуешь там их передай

2022-09-09 11:43 UTC, Spaider15 commented on src/components/Input/index.module.css
> +    font-size: 14px;
цвет лейбла color: #162833;

2022-09-09 11:43 UTC, Spaider15 commented on src/components/Input/index.module.css
> +    position: relative;
это обязательно? давай постараемся избегать не нужного абсолютного позиционирования

2022-09-09 11:43 UTC, Spaider15 commented on src/components/Input/index.module.css
> +    display: flex;
инпуту вроде не нужно display: flex и все остальные flex свойства тоже лишние

2022-09-09 11:43 UTC, Spaider15 commented on src/components/Input/index.module.css
> +    position: relative;
position: relative; снова

2022-09-12 10:21 UTC, Spaider15 approved these changes

2022-09-12 10:21 UTC, merged