Collapse
diekuche/gutenberg pull request #14
Opened 2022-09-09 09:09 UTC by Xyzjesus

## Задача по верстке: прикладывайте скриншот результата верстки, рядом скриншот макета, что бы я мог сравнить.
![image](https://user-images.githubusercontent.com/62913761/189314596-8855b3e9-4d9f-43d5-8f18-c18583eb0ba1.png)
![image](https://user-images.githubusercontent.com/62913761/189314681-6bbe847e-afa4-492e-bedf-fa417c95447b.png)
![image](https://user-images.githubusercontent.com/62913761/189314814-d58da952-106e-4ece-b70e-0a112625957b.png)

## Задача по логике: краткое описание того, что было сделано, если что-то сложное то можно приложить видео

прописать пропсы title и children

# Ссылка на issue:
https://github.com/diekuche/gutenberg/issues/4#issue-1365685016

2022-09-09 11:50 UTC, Spaider15 requested changes

2022-09-09 11:50 UTC, Spaider15 commented on src/components/Collapsible/Collapsible.tsx
> +                <div className={styles.children}>
Здесь контент у тебя хардкодный а должно быть {children}
Пример использования:
```
<Collapsible  title="my title">{<Input />}<Collapsible />
```

2022-09-09 11:50 UTC, Spaider15 commented on src/components/Collapsible/Collapsible.tsx
> +export const Collapsible = (props: CollapsibleProps) => {
Функциональный компонент, молодец

2022-09-09 11:50 UTC, Spaider15 commented on src/components/Collapsible/Collapsible.tsx
> +    children?: string;
Убери здесь children, а ниже напиши:
```
export const Collapsible: React.FC<CollapsibleProps> = (props: CollapsibleProps) => {
```

2022-09-09 11:50 UTC, Spaider15 commented on src/components/Collapsible/index.module.css
> +    position: absolute;
убираем

2022-09-09 11:50 UTC, Spaider15 commented on src/App.tsx
> +        title="+Change Initial Balances"
Плюс не должен указываться в тайтле, это должна быть иконка, указывает что этот компонент может разворачиваться, когда компонент развернут она должна меняться на минус

2022-09-12 12:58 UTC, Xyzjesus commented on src/App.tsx
> +        title="+Change Initial Balances"
@Spaider15 не могу понять с плюсом, там надо как-то тоже через useState и состояние isActive проверять?

2022-09-14 07:34 UTC, Xyzjesus commented
@Spaider15 Допилил + и -, мерджим?

2022-09-14 09:41 UTC, Spaider15 approved these changes

2022-09-14 09:41 UTC, merged