add form
diekuche/gutenberg pull request #17
Opened 2022-09-12 14:31 UTC by Xyzjesus

## Задача по верстке: прикладывайте скриншот результата верстки, рядом скриншот макета, что бы я мог сравнить.

![image](https://user-images.githubusercontent.com/62913761/189680066-3b22153e-f094-420a-b759-202f865b66be.png)
![image](https://user-images.githubusercontent.com/62913761/189680169-d914814c-5f8a-4ea1-b8cd-3813d5b120a3.png)

## Задача по логике: краткое описание того, что было сделано, если что-то сложное то можно приложить видео
использовал абсолютное позиционирование, размеры vw и vh взяты из расчета 1414px ширины макета 

# Ссылка на issue: https://github.com/diekuche/gutenberg/issues/11#issue-1367363763

2022-09-13 06:44 UTC, Spaider15 commented
@Xyzjesus высота инпута 60px, должна быть 36
отступ между инпутами должен быть 10px, сейчас 20, вообще у самого инпута лучше убрать внешний паддинг

2022-09-13 06:47 UTC, Spaider15 requested changes

2022-09-13 06:47 UTC, Spaider15 commented on src/components/Form/index.module.css
> +    width: 42.14vw;
В макете у формы фиксированная ширина 590px давай ее использовать

2022-09-13 06:47 UTC, Spaider15 commented on src/components/Form/index.module.css
> +    position: absolute;
убери absolute плиз

2022-09-13 06:47 UTC, Spaider15 commented on src/components/Form/index.module.css
> +    display: flex;
зачем заголовку display flex?
используй плиз классы вместо тегов, в этом смысл css modules

2022-09-13 06:47 UTC, Spaider15 commented on src/components/Form/index.module.css
> +    width: 42.14vw;
И инпутам плиз сделай ширину 100%, пусть родитель ограничивает их ширину

2022-09-13 06:47 UTC, Spaider15 commented on src/components/Form/Form.tsx
> +                subtitle={``}
сделай subtitle опциональным атрибутом раз он нам не всегда нужен, а в компоненте рендери его если только его передали
```
{subtitle && <div>....</div>}
```

2022-09-13 06:47 UTC, Spaider15 commented on src/components/Form/Form.tsx
> +                type={`text`}
что бы не писать это в каждом компоненте, сделай параметр опциональным и по умолчанию присвой ему значение text

2022-09-13 06:55 UTC, Xyzjesus commented on src/components/Form/index.module.css
> +    width: 42.14vw;
> В макете у формы фиксированная ширина 590px давай ее использовать

а мы потом не будем переделывать это под резиновый дизайн с размером в vw?

2022-09-13 06:57 UTC, Xyzjesus commented on src/components/Form/index.module.css
> +    display: flex;
> зачем заголовку display flex? используй плиз классы вместо тегов, в этом смысл css modules

а положение с атрибутом justify-content меняется не только в случае с flex?

2022-09-13 16:23 UTC, Spaider15 requested changes

2022-09-13 16:23 UTC, Spaider15 commented on src/components/Input/Input.tsx
> +    type: `text`,
под значением по умолчанию я имел ввиду вот это: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters

2022-09-13 16:23 UTC, Spaider15 commented on src/components/Input/Input.tsx
> +                <div className={styles.subtitle}>{(subtitle && <div>{subtitle}</div>) || ""}</div>
смысл проверки в том что бы не рендерить пустой див, а здесь он у тебя все равно будет

2022-09-13 16:34 UTC, Xyzjesus commented on src/components/Input/Input.tsx
> +                <div className={styles.subtitle}>{(subtitle && <div>{subtitle}</div>) || ""}</div>
|| убрать? Ничего не передавать в else?

2022-09-13 16:40 UTC, Xyzjesus commented on src/components/Input/Input.tsx
> +    type: `text`,
@Spaider15 а это решение не подойдёт? Пропс не передаёт дефолтное значение в компонент?

2022-09-13 17:03 UTC, Spaider15 commented on src/components/Input/Input.tsx
> +                <div className={styles.subtitle}>{(subtitle && <div>{subtitle}</div>) || ""}</div>
`{subtitle && <div className={styles.subtitle}>{subtitle}</div>}`

2022-09-13 17:04 UTC, Spaider15 commented on src/components/Input/Input.tsx
> +    type: `text`,
@Xyzjesus поставь console.log(props) и посмотри, я не думаю это же типы

2022-09-14 08:08 UTC, Xyzjesus commented on src/components/Input/Input.tsx
> +                <div className={styles.subtitle}>{(subtitle && <div>{subtitle}</div>) || ""}</div>
@Spaider15 а блин( все было пррще) ну теперь знать буду

2022-09-15 06:55 UTC, Spaider15 approved these changes

2022-09-15 06:55 UTC, merged