button active and hover
diekuche/gutenberg pull request #23
Opened 2022-09-15 09:15 UTC by scsi9

## Задача по верстке: прикладывайте скриншот результата верстки, рядом скриншот макета, что бы я мог сравнить.

## Задача по логике: краткое описание того, что было сделано, если что-то сложное то можно приложить видео

# Ссылка на issue:
https://prnt.sc/60mlO4UnSO4v - кнопка
https://prnt.sc/LEsYjc232kK9 - состояние Active

2022-09-15 09:16 UTC, scsi9 commented
https://prnt.sc/iZr7n6EdnCak кнопка
https://prnt.sc/a8-8IRDx1FGM когда Active
верстка на форме, ее сделал чтобы скрины приложить

2022-09-15 09:18 UTC, scsi9 commented
![image](https://user-images.githubusercontent.com/17857895/190366080-e03dd6f1-2081-476c-810c-7ed21d1548b4.png)
кнопка
состояние Active
![image](https://user-images.githubusercontent.com/17857895/190366189-97b19141-2caa-4ee9-95f2-aa2338ae999e.png)

2022-09-15 10:50 UTC, scsi9 commented
https://user-images.githubusercontent.com/17857895/190385527-90e612f9-1679-4017-95b0-faf27fd36181.mp4

2022-09-15 11:49 UTC, Spaider15 requested changes

2022-09-15 11:49 UTC, Spaider15 commented on src/components/ButtonSend/ButtonSend.module.css
> +    width: 114px;
не нужно делать фиксированную ширину, текст внутри кнопки может быть разным, может быть длинней чем 114px

2022-09-15 11:49 UTC, Spaider15 commented on src/components/ButtonAddToken/ButtonAddToken.module.css
> +    width: 114px;
здесь тоже фиксированная ширина

2022-09-15 11:49 UTC, Spaider15 commented on src/components/ButtonAddToken/ButtonAddToken.module.css
> +   opacity: 0;
opacity 0 делает кнопку невидимой, не уверен это то что нам нужно, уточни плиз лучше в чате

2022-09-16 07:52 UTC, scsi9 commented
Убрал фиксированную ширину с Send и Token
Изменил свойство при Disabled

2022-09-16 12:12 UTC, Spaider15 approved these changes

2022-09-16 12:12 UTC, merged