Tabs3
diekuche/gutenberg pull request #25
Opened 2022-09-19 13:40 UTC by scsi9

## Задача по верстке: прикладывайте скриншот результата верстки, рядом скриншот макета, что бы я мог сравнить.

## Задача по логике: краткое описание того, что было сделано, если что-то сложное то можно приложить видео

# Ссылка на issue:
![image](https://user-images.githubusercontent.com/17857895/191030683-36abea60-b4dc-470e-a1e7-571a93c123f2.png)

2 дня искала как реализовать табсы, ну чтобы работало переключение по кликам, не смог сделать - нужна помощь

2022-09-19 13:50 UTC, Spaider15 requested changes

2022-09-19 13:50 UTC, Spaider15 commented on src/components/Tabs/Tabs.module.css
> +  width: 230px;
не ставь плиз фиксированную ширину, текст может быть разный

2022-09-19 13:50 UTC, Spaider15 commented on src/components/Tabs/Tabs.module.css
> +  display: inline-flex;
а зачем тебе здесь флекс? там же нет вложенных элементов

2022-09-19 13:50 UTC, Spaider15 commented on src/components/Tabs/Tabs.module.css
> +  width: 125px;
фиксированная ширина

2022-09-19 13:50 UTC, Spaider15 commented on src/components/Tabs/Tabs.module.css
> +  display: inline-flex;
здесь флекс тоже не нужен

2022-09-19 13:50 UTC, Spaider15 commented on src/components/Tabs/Tabs.module.css
> +  color: #D3FF54;;
двойные ковычки

2022-09-19 14:04 UTC, scsi9 commented on src/components/Tabs/Tabs.module.css
> +  display: inline-flex;
если убираю флекс вообще - пропадает выравнивание по центру

2022-09-20 04:48 UTC, Spaider15 commented on src/components/Tabs/Tabs.module.css
> +  display: inline-flex;
@scsi9 обрати внимание как в фигме достигается выравнивание, и сделай так же 
<img width="305" alt="image" src="https://user-images.githubusercontent.com/12617760/191169894-561a4e05-738f-49c7-a140-8c720b32da2b.png">

2022-09-20 09:07 UTC, scsi9 commented
![image](https://user-images.githubusercontent.com/17857895/191217292-59728620-a732-42f3-9ff1-f7a98db0a3ce.png)

2022-09-20 12:54 UTC, merged