bug fixing
diekuche/gutenberg pull request #64
Opened 2022-11-22 19:06 UTC by Xyzjesus

## Задача по верстке: прикладывайте скриншот результата верстки, рядом скриншот макета, что бы я мог сравнить.

## Задача по логике: краткое описание того, что было сделано, если что-то сложное то можно приложить видео
![image](https://user-images.githubusercontent.com/62913761/203398749-aad4e0d2-0afd-452f-89b8-f1b897564a13.png)
1.added default decimals and balance if it's not mentioned
![image](https://user-images.githubusercontent.com/62913761/203399125-7c250fc4-4ed2-4078-ab9b-916918ddd8a6.png)
![image](https://user-images.githubusercontent.com/62913761/203399224-0a7e3cd2-aea1-4a8a-885a-3c9e6fe658a2.png)

![image](https://user-images.githubusercontent.com/62913761/203399299-2a453efe-cc09-4adb-9b7a-45ee7a5eba93.png)
2. pop-up added 
![image](https://user-images.githubusercontent.com/62913761/203399338-561b69b3-c46d-4977-bbd5-f1cb16cc48c9.png)

![image](https://user-images.githubusercontent.com/62913761/203399505-b3f5089e-32fa-487a-97e3-24bb8c729b85.png)
3. add disconnect func and button change 
![image](https://user-images.githubusercontent.com/62913761/203399584-7e279653-6172-4a82-9572-c48477890014.png)
![image](https://user-images.githubusercontent.com/62913761/203399616-1c538e86-659e-4673-81b6-f95277f01432.png)

![image](https://user-images.githubusercontent.com/62913761/203399729-d40bfd4d-b9cd-467f-876c-c4596ad333c6.png)
4. change BOOT name and first click on button
![image](https://user-images.githubusercontent.com/62913761/203399851-82aa78f0-1980-406a-9832-513047e0f082.png)
![image](https://user-images.githubusercontent.com/62913761/203399899-6f130295-4064-4004-9bec-7f21d36b1894.png)

# Ссылка на issue: https://github.com/diekuche/gutenberg/issues/61

2022-11-23 06:51 UTC, Spaider15 requested changes

2022-11-23 06:51 UTC, Spaider15 commented on src/components/Form/Form.tsx
> +import "react-toastify/dist/ReactToastify.css";
стили и контейнер нужно вынести в app.tsx

2022-11-23 06:51 UTC, Spaider15 commented on src/contracts/base/contract.ts
> +        localStorage.setItem("txHash", JSON.stringify(result.transactionHash));
в чем проблема вернуть result.transactionHash, вместо установки значения в localStorage?

2022-11-23 06:51 UTC, Spaider15 commented on src/components/Form/Form.tsx
> +        initialBalance.address = initialAddress;
а зачем здесь менять initialBalance если он дальше не используется?

2022-11-23 06:51 UTC, Spaider15 commented on src/components/Wallet/Wallet.tsx
> +    event.target.style.background = "red";
В реакте так не нужно делать, используй классы

2022-11-23 06:51 UTC, Spaider15 commented on src/components/Wallet/Wallet.tsx
> +    `${address.slice(0, 10)}...${address.slice(-10, -5)}` || `disconnect`
|| никогда не сработает, т.к. в первом условии будет всегда строка

2022-11-23 06:51 UTC, Spaider15 commented on src/components/Wallet/Wallet.tsx
> +    } else if (address) {
ты проверяешь уже на то что адреса нет, в else адрес ну точно будет, в этой проверке нет смысла

2022-11-23 06:51 UTC, Spaider15 commented on src/components/Wallet/Wallet.tsx
> +    setDisconnect(`${address.slice(0, 10)}...${address.slice(-10, -5)}`);
почему функция называется setDisconnect, а ты туда кладешь адрес контракта?

2022-11-23 06:51 UTC, Spaider15 commented on src/utils/wallet.ts
> +      return console.log("disconnected", result);
console log вроде ничего не возвращает

2022-11-24 06:38 UTC, Xyzjesus commented
removing tokens added
![image](https://user-images.githubusercontent.com/62913761/203711563-cbb43504-afe1-44bc-ac74-bec244654935.png)
![image](https://user-images.githubusercontent.com/62913761/203711576-89def541-8301-44ed-9fa6-0bd019021e03.png)

2022-11-24 11:09 UTC, Spaider15 approved these changes

2022-11-24 11:09 UTC, merged