Sticky
diekuche/gutenberg pull request #86
Opened 2023-01-11 06:34 UTC by scsi9

## Задача по верстке: прикладывайте скриншот результата верстки, рядом скриншот макета, что бы я мог сравнить.

## Задача по логике: краткое описание того, что было сделано, если что-то сложное то можно приложить видео

# Ссылка на issue:
![image](https://user-images.githubusercontent.com/17857895/211734861-57bd9f86-b387-413d-b4a2-d32ab8d171ec.png)

2023-01-12 09:50 UTC, Spaider15 requested changes

2023-01-12 09:50 UTC, Spaider15 commented on src/components/HeaderSpoiler/HeaderSpoiler.tsx
> +  const [header, setHeader] = useState("header");
здесь оставил класс строкой

2023-01-12 09:50 UTC, Spaider15 commented on src/components/HeaderSpoiler/HeaderSpoiler.tsx
> +    window.addEventListener("scroll", listenScrollEvent);
функцию listenScrollEvent перенеси внутрь useEffect

2023-01-12 09:50 UTC, Spaider15 commented on src/components/HeaderSpoiler/index.module.css
> +  height: 70px;
у header и header2 есть повторяющиеся стили убери их

2023-01-12 09:50 UTC, Spaider15 commented on src/components/Main/Main.tsx
> +      <div className="colorhead">
почему класс строкой?

2023-01-12 09:50 UTC, Spaider15 commented on src/components/ManageTok/ManageTok.module.css
> +  height: 529px;
убери фиксированную высоту

2023-01-12 09:50 UTC, Spaider15 commented on src/components/ManageTok/ManageTok.module.css
> +  margin-left: 244 px;
<img width="189" alt="image" src="https://user-images.githubusercontent.com/12617760/212034094-9ace9761-8506-491b-b1e5-073ffb381869.png">
это не валидный css

2023-01-12 11:45 UTC, scsi9 commented on src/components/HeaderSpoiler/HeaderSpoiler.tsx
> +    window.addEventListener("scroll", listenScrollEvent);
+

2023-01-12 11:46 UTC, scsi9 commented on src/components/HeaderSpoiler/HeaderSpoiler.tsx
> +  const [header, setHeader] = useState("header");
+

2023-01-12 12:03 UTC, scsi9 commented on src/components/HeaderSpoiler/index.module.css
> +  height: 70px;
+

2023-01-12 12:27 UTC, scsi9 commented on src/components/Main/Main.tsx
> +      <div className="colorhead">
+

2023-01-12 12:28 UTC, scsi9 commented on src/components/ManageTok/ManageTok.module.css
> +  height: 529px;
+

2023-01-13 06:27 UTC, Spaider15 approved these changes

2023-01-13 06:28 UTC, merged