redisignButtons84
diekuche/gutenberg pull request #90
Opened 2023-01-18 11:09 UTC by scsi9

## Задача по верстке: прикладывайте скриншот результата верстки, рядом скриншот макета, что бы я мог сравнить.

## Задача по логике: краткое описание того, что было сделано, если что-то сложное то можно приложить видео

# Ссылка на issue:
layout - 
![image](https://user-images.githubusercontent.com/17857895/213155300-14ddd3b6-5e9f-4643-a0e3-97beb09504ea.png)
Figma - https://www.figma.com/file/xQoRnWDlMtEUSG7WcKqlzB/GUT!?node-id=245%3A1934&t=jlcfUwxjW19Nu2t8-0
created buttons at http://localhost:3000/newBT

2023-01-19 06:35 UTC, Spaider15 requested changes

2023-01-19 06:35 UTC, Spaider15 commented on src/components/newButton/newButton.module.css
> +  width: 170px;
фиксированные размеры убери

2023-01-19 06:35 UTC, Spaider15 commented on src/components/newButton/newButton.module.css
> +  height: 36px;
и здесь

2023-01-19 06:35 UTC, Spaider15 commented on src/components/newButton/newButton.module.css
> +  width: 18px;
и здесь

2023-01-19 10:21 UTC, scsi9 commented on src/components/newButton/newButton.module.css
> +  width: 170px;
+

2023-01-19 10:21 UTC, scsi9 commented on src/components/newButton/newButton.module.css
> +  height: 36px;
+

2023-01-19 10:21 UTC, scsi9 commented on src/components/newButton/newButton.module.css
> +  width: 18px;
+

2023-01-23 09:25 UTC, Spaider15 approved these changes

2023-01-23 09:26 UTC, merged