swap
diekuche/gutenberg pull request #95
Opened 2023-02-01 10:42 UTC by scsi9

## Задача по верстке: прикладывайте скриншот результата верстки, рядом скриншот макета, что бы я мог сравнить.

## Задача по логике: краткое описание того, что было сделано, если что-то сложное то можно приложить видео

# Ссылка на issue:
layout - 
![image](https://user-images.githubusercontent.com/17857895/216021072-7cf9615c-35d0-4850-ab7d-555befb8ca34.png)
figma - 
![image](https://user-images.githubusercontent.com/17857895/216021224-af270331-aa16-429a-9ea0-c7319576750d.png)

2023-02-01 11:02 UTC, scsi9 commented
layout - 
![image](https://user-images.githubusercontent.com/17857895/216025031-6bedfa9c-3b6a-4968-8267-833f00bee839.png)

2023-02-01 11:29 UTC, Spaider15 requested changes

2023-02-01 11:29 UTC, Spaider15 commented on src/components/Swap/Swap.module.css
> +.lowerselect {
здесь дублируются все стили как у .select

2023-02-01 11:29 UTC, Spaider15 commented on src/components/Swap/Swap.module.css
> +  padding: 20px 170px;
кнопку переиспользуй, не копируй стили для нее

2023-02-06 06:02 UTC, Spaider15 approved these changes

2023-02-06 06:02 UTC, merged